#!/usr/bin/env ruby
require File.expand_path('../../config/boot',  __FILE__)
if RAILS_ENV == 'development'
  logfile = File.join(RAILS_ROOT,'log','mailtrap.log')
  system('mailtrap','start','--file',logfile)
  begin
    require 'commands/server'
  ensure
    system('mailtrap','stop')
  end
else
  require 'commands/server'
end
